#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jul  4 11:25:35 2017

@author: thelma
"""

def dict_invert(d):
    '''
    d: dict
    Returns an inverted dictionary according to the instructions above
    '''
    
    d = {8: 6, 2: 6, 4: 6, 6: 6}
    inverse = {}

    for key in d:
        val = d[key]
        if val not in inverse:
            inverse[val] = [key]
        else:
            inverse[val].append(key)
        
    for key in inverse:
        inverse[key].sort()

    return inverse