#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jun 15 15:59:11 2017

@author: thelma
"""
"""
Calculate lowest monthly rate for credit to be paid off in 12 months '/'
using bisection search.
Input: positive int balance, positive float annualInterestRate
Output: lowest monthly rate as float, rounded to 2 decimals.
"""
balance = 999999    # Value given
annualInterestRate = 0.18   # Value given
low = balance / 12
high = balance * ((1+annualInterestRate/12)**12) / 12

while True:
    testbalance = balance
    guess = (high+low) / 2
    
    # Calculate total annual credit including interest
    for m in range(1,13):
        unpaid = testbalance - guess
        testbalance = unpaid + unpaid * annualInterestRate / 12

    # Bisection search
    if round(testbalance, 2) < 0:
        high = guess
        
    elif round(testbalance, 2) > 0:
        low = guess
        
    else:
        print(round(guess, 2))
        break
    
    
