#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jun  7 14:30:50 2017

@author: thelma
"""
s = 'This is great!'

def print_without_vowels(s):
    """
    s: the string to convert
    Finds a version of s without vowels and whose characters appear in the same
    order they appear in s. Prints this version of s. 
    Does not return anything
    """
    new_string = ''
    for letter in s:
        if letter not in 'aeiouAEIOU':
            new_string += letter
    print(new_string)
    
print_without_vowels(s)